import fs from "fs"
import path from "path"

const appDir = path.join(process.cwd(), "app")
const localeDir = path.join(appDir, "[locale]")
const defaultDir = path.join(appDir, "(default)")

const MIRRORED_FILES = new Set<string>(["page.tsx", "layout.tsx"])
const AUTO_HEADER = "// AUTO-GENERATED by scripts/sync-default-pages.ts"

// Recursively list all files in a directory.
function walk(dir: string): string[] {
  if (!fs.existsSync(dir)) return []
  const entries = fs.readdirSync(dir, { withFileTypes: true })
  const files: string[] = []

  for (const entry of entries) {
    const fullPath = path.join(dir, entry.name)
    if (entry.isDirectory()) {
      files.push(...walk(fullPath))
    } else {
      files.push(fullPath)
    }
  }

  return files
}

function ensureDir(dir: string): void {
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true })
  }
}

function writeIfChanged(filePath: string, content: string): void {
  if (fs.existsSync(filePath)) {
    const existing = fs.readFileSync(filePath, "utf8")
    if (existing === content) return
  }
  fs.writeFileSync(filePath, content, "utf8")
  console.log("Updated:", path.relative(process.cwd(), filePath))
}

function removeExtension(p: string): string {
  return p.replace(/\.[^.]+$/, "")
}

// Remove auto-generated files in (default) that no longer have a matching file in [locale].
function cleanupOrphans(expectedDefaultFiles: Set<string>): void {
  const defaultFiles = walk(defaultDir)

  for (const filePath of defaultFiles) {
    const basename = path.basename(filePath)

    // Only care about files we generate (page/layout)
    if (!MIRRORED_FILES.has(basename)) continue
    if (expectedDefaultFiles.has(filePath)) continue

    // Only delete files that we know we generated (safety)
    try {
      const content = fs.readFileSync(filePath, "utf8")
      if (!content.startsWith(AUTO_HEADER)) continue

      fs.unlinkSync(filePath)
      console.log("Removed stale default page:", path.relative(process.cwd(), filePath))
    } catch (err) {
      console.warn("Failed to inspect or delete file:", filePath, err)
    }
  }

  // Clean up empty directories under (default)
  const dirs = new Set<string>()
  for (const filePath of defaultFiles) {
    dirs.add(path.dirname(filePath))
  }

  const sortedDirs = Array.from(dirs).sort((a, b) => b.length - a.length) // deepest first

  for (const dir of sortedDirs) {
    if (dir === defaultDir) continue // never delete root
    try {
      const entries = fs.readdirSync(dir)
      if (entries.length === 0) {
        fs.rmdirSync(dir)
        console.log("Removed empty directory:", path.relative(process.cwd(), dir))
      }
    } catch {
      // ignore errors (e.g., already removed)
    }
  }
}

function main(): void {
  if (!fs.existsSync(localeDir)) {
    console.error("Could not find app/[locale] directory at:", localeDir)
    process.exit(1)
  }

  ensureDir(defaultDir)

  const allFiles = walk(localeDir)

  const targetFiles = allFiles.filter((file) => MIRRORED_FILES.has(path.basename(file)))

  const expectedDefaultFiles = new Set<string>()

  if (targetFiles.length === 0) {
    console.log("No page/layout files found under app/[locale].")
  } else {
    for (const localeFilePath of targetFiles) {
      const relativeFromLocale = path.relative(localeDir, localeFilePath)
      const defaultFilePath = path.join(defaultDir, relativeFromLocale)
      expectedDefaultFiles.add(defaultFilePath)

      const defaultDirPath = path.dirname(defaultFilePath)
      ensureDir(defaultDirPath)

      let importPath = path.relative(defaultDirPath, localeFilePath)
      importPath = importPath.split(path.sep).join("/")

      if (!importPath.startsWith(".")) {
        importPath = "./" + importPath
      }

      importPath = removeExtension(importPath)

      const content =
        `${AUTO_HEADER}\n` +
        `// Do not edit this file directly.\n\n` +
        `export { default } from "${importPath}";\n` +
        `export * from "${importPath}";\n`

      writeIfChanged(defaultFilePath, content)
    }
  }

  // Remove stale generated files in (default)
  cleanupOrphans(expectedDefaultFiles)

  console.log("Finished syncing default pages.")
}

main()
